name: cron

instance_groups:
- name: cron
  instances: 1
  azs:       [z1]
  stemcell:  default
  vm_resources:
    cpu: 2
    ram: 2048
    ephemeral_disk_size: 8192
  networks:
    - name: default
  jobs:
    - release: cron
      name:    cron
      properties:
        cron:
          entries:
            - log: /var/vcap/sys/log/cron/out.log
              minute: 0
              hour: '*'
              day: '*'
              month: '*'
              wday: '*'
              user: root
              script:
                name: touch.sh
                contents: |
                  #!/bin/bash
                  set -x
                  echo Hello, World

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
- alias:   default
  os:      ubuntu-xenial
  version: latest

releases:
- name:    cron
  version: 1.3.0
  url:     https://github.com/cloudfoundry-community/cron-boshrelease/releases/download/v1.3.0/cron-1.3.0.tgz
  sha1:    fb5ea977eefe8ef3f51754db54c3a7a31f971caf
